kyma-project/examples

- call-ec/Jenkinsfile
- event-email-service/Jenkinsfile
> Fix Checkmarx scan

- CODEOWNERS
---
- Clean up old members from code owners
> Cleanup code owners

- call-ec/README.md
- call-ec/web-ui/deployment.yaml
- gateway/README.md
- gateway/lambda/api-with-default-auth.yaml
- gateway/lambda/api-without-auth.yaml
- gateway/service/api-with-default-auth.yaml
- gateway/service/api-without-auth.yaml
---
- Add example of exposing Api with default authentication config
- Fix ingress mentions in READMEs
- Fix not proper Api resources
**Issue link**
See also https://github.com/kyma-project/kyma/pull/18
> Fixes related to changes in api controller after migration to istio gateway

- README.md
> Remove the section link from the main README.md

- CONTRIBUTING.md
- monitoring-custom-metrics/README.md
---
- Fix broken links
-
-
**Issue link**
> Fix broken links

- governance.Jenkinsfile
- milv.config.yaml
---
- Enable external links validation on master branch
- Enable internal links validation on PR
- Send notification to Slack channel when `governance` validation fails on master
**Issue link**
> Enable internal/external links validation

- service-binding/lambda/deployment/service-binding-usage.yaml
- service-binding/service/deployment/mssql-binding-usage.yaml
---
- Adjusted SBU examples after UsageKind implementation
> Adjust ServiceBindingUsage examples

- monitoring-custom-metrics/deployment/deployment.yaml
---
- Bump image for custom monitoring metrics
> Bump image for custom metrics application

- CONTRIBUTING.md
- event-subscription/lambda/README.md
- governance.Jenkinsfile
- milv.config.yaml
- service-binding/lambda/README.md
---
- Update dead links
- Bump version of milv bot to 0.0.4 in `governance` job
> Update dead links and bump version of milv in governance job

- CONTRIBUTING.md
- Update the CONTRIBUTING.md document with the information on the manual CI run step
Relates to issue`#50` in the community repository
> Update the CONTRIBUTING.md document with the manual CI running info

- event-subscription/lambda/deployment/subscription.yaml
- event-subscription/service/example-subscription.yaml
- remove the `include_topic_header` from the event subscription examples
https://github.com/kyma-project/kyma/issues/387
> Remove include topic header option from event subscription examples 

- http-db-service/Jenkinsfile
- monitoring-custom-metrics/Jenkinsfile
- tests/http-db-service/Jenkinsfile
> Disable sourceclear

- call-ec/Jenkinsfile
- event-email-service/Jenkinsfile
- monitoring-custom-metrics/Jenkinsfile
- Check why checkmarx is failing
> Check checkmarx

- CODEOWNERS
---
- add codeowners of `milv` bot in `CODEOWNERS` file
> Add codeowners for milv bot

- http-db-service/handler/api.go
- http-db-service/handler/api_test.go
- http-db-service root now shows API specification in the swagger editor
> http-db-service API improvements

- http-db-service/docs/api/api.yaml
- http-db-service/handler/api.go
- Fix APPI spec tags
- Fix wrong swagger parameter call
> Fix http-db-service API

- Jenkinsfile
- event-email-service/Jenkinsfile
- event-email-service/README.md
- event-subscription/lambda/README.md
- event-subscription/lambda/deployment/sample-publisher.yaml
- examples-chart/templates/deployments/event-email-service/Pod.yaml
- examples-chart/templates/deployments/http-db-service/Pod.yaml
- examples-chart/values.yaml
- http-db-service/Jenkinsfile
- http-db-service/README.md
- orchestrator.Jenkinsfile
---
- Enhances examples pipeline by enabling deployment of examples onto a cluster. 
- Includes several changes on the examples simply to trigger/test the deployment.
-
**Issue link**
> Enable automated deployment of examples

- call-ec/README.md
- Fixed a dead link
See also https://github.com/kyma-project/kyma/issues/611
> Fix a dead link

- event-subscription/lambda/README.md
- event-subscription/lambda/deployment/event-activation.yaml
- event-subscription/lambda/deployment/subscription.yaml
- event-subscription/service/README.md
- event-subscription/service/example-event-activation.yaml
- event-subscription/service/example-subscriber.yaml
- event-subscription/service/example-subscription.yaml
- examples-chart/templates/deployments/pre-install-rbac.yaml
Update examples EventActivation & Subscription CRDs to latest specs as defined [here](https://github.com/kyma-project/kyma/tree/master/resources/cluster-essentials/templates)
- Update CRDs of `event-subscription` example
- Update `pre-install-rbac.yaml` of `example chart`
#41
> Update examples EventActivation & Subscription CRDs to latest specs

- call-ec/Jenkinsfile
- event-email-service/Jenkinsfile
- http-db-service/Jenkinsfile
- monitoring-custom-metrics/Jenkinsfile
- tests/http-db-service/Jenkinsfile
- Update golang buildpack version
- Temporarily disable Whitesource
> Update golang buildpack version and disable Whitesource

- call-ec/Jenkinsfile
- event-email-service/Jenkinsfile
> Enable Whitesource

- CODEOWNERS
> Add aerfio for CODEOWNERS

- event-email-service/Jenkinsfile
- Add user key to whitesource configuration
> Add user key to whitesource configuration

- governance.Jenkinsfile
- orchestrator.Jenkinsfile
- Disable external links validation on master
See also https://github.com/kyma-project/kyma/issues/1290
> Disable external links validation on master

- Jenkinsfile
- examples-chart/templates/tests/service-binding/lambda/Pod.yaml
- resourceQuota.yaml
- service-binding/lambda/deployment/redis-instance.yaml
- Increase resource quota for a namespace
> Increase resource quota for a namespace

- milv.config.yaml
- Whitelist a link with domain variable
> Whitelist a link with a domain variable

- milv.config.yaml
- Update link in `milv.config.yaml`
> Update link in milv.config.yaml

- call-ec/README.md
- call-ec/expose-ec-function.yaml
- call-ec/web-ui/deployment.yaml
- gateway/lambda/api-with-auth.yaml
- gateway/lambda/api-with-default-auth.yaml
- gateway/lambda/api-without-auth.yaml
- gateway/service/api-with-auth.yaml
- gateway/service/api-with-default-auth.yaml
- gateway/service/api-without-auth.yaml
- tracing/README.md
- tracing/deployment/deployment.yaml
Removed host suffixes for all api resources
> use short host names in api resources

- call-ec/expose-ec-function.yaml
- call-ec/web-ui/deployment.yaml
- gateway/lambda/api-with-auth.yaml
- gateway/lambda/api-with-default-auth.yaml
- gateway/lambda/api-without-auth.yaml
- gateway/service/api-with-auth.yaml
- gateway/service/api-with-default-auth.yaml
- gateway/service/api-without-auth.yaml
adjusts all api group names to "gateway.kyma-project.io"
> fixes api crd group name

- Jenkinsfile
- Disable test for service-binding lambda example
> Disable test for service-binding lambda example

- README.md
- Updated the link in the README.md to the new document that changes to the **Examples** type.
See also https://github.com/kyma-project/kyma/issues/1730
> Update the link

- examples-chart/templates/deployments/pre-install-rbac.yaml
- service-binding/lambda/deployment/lambda-function.yaml
- service-binding/service/deployment/http-db-service.yaml
- Adjusted BUC CRs domain to kyma-project.io
> Adjust BUC CRs domain to kyma-project.io

- call-ec/README.md
- event-email-service/README.md
- event-subscription/lambda/README.md
- event-subscription/lambda/deployment/subscription.yaml
- event-subscription/service/README.md
- event-subscription/service/example-subscription.yaml
- examples-chart/README.md
- examples-chart/templates/deployments/event-subscription/lambda/Pod.yaml
- gateway/README.md
- http-db-service/README.md
- monitoring-alert-rules/README.md
- monitoring-custom-metrics/README.md
- service-binding/lambda/README.md
- service-binding/service/README.md
- tracing/README.md
- Rename Environment to Namespace
> Rename Environment to Namespace

- event-subscription/service/README.md
> Fix broken link

- CODEOWNERS
> Add suleymanakbas91 to Codeowners

- monitoring-alert-rules/deployment/alert-rule-configmap.yaml
> Fix alert rule

- event-subscription/lambda/README.md
- event-subscription/service/README.md
- examples-chart/templates/tests/event-subscription/lambda/Pod.yaml
- Fixed url for publishing events
> Fix url for publishing events

- monitoring-custom-metrics/deployment/service-monitor.yaml
> Fix service monitor

- event-subscription/service/README.md
- Fix the event-subscription service example.
> Fix the event-subscription service example

- event-subscription/lambda/README.md
- http-db-service/Gopkg.lock
- http-db-service/README.md
- monitoring-alert-rules/README.md
- monitoring-custom-metrics/README.md
- service-binding/lambda/README.md
This PR contains various fixes for kyma-examples. Fixes the following issues: #108 and #109
> Various fixes for kyma-examples

- monitoring-alert-rules/README.md
- monitoring-custom-metrics/README.md
- Fixed monitoring examples - changed `core-prometheus` to `monitoring-prometheus`
> Fix monitoring examples

- gateway/README.md
- Added note about API amount per service 
#107
> Fix gateway example

- http-db-service/build.sh
- Remove unused variables in `http-db-service/build.sh`
- Prevent globbing and word splitting (shellcheck rule SC2086) in `http-db-service/build.sh`
> Polish build script in http-db-service

- README.md
- event-email-service/README.md
- event-subscription/lambda/README.md
- event-subscription/service/README.md
- examples-chart/README.md
- gateway/README.md
- http-db-service/README.md
- monitoring-custom-metrics/README.md
- service-binding/lambda/README.md
- service-binding/service/README.md
- tracing/README.md
> Fix dead links

- http-db-service/deployment/deployment.yaml
See also https://github.com/kyma-project/kyma/issues/3960
> Update the image version for http-db-service

- event-subscription/lambda/README.md
- event-subscription/lambda/js/hello-with-data.js
- event-subscription/service/README.md
- Making event-bus examples  CE spec 3.0 compliant
See https://github.com/kyma-project/kyma/issues/4388
> Making event-bus examples CE spec 3.0 compliant

- event-subscription/lambda/deployment/subscription.yaml
- event-subscription/service/example-subscription.yaml
- Update the Kyma subscription by removing both the **max_inflight** and **push_request_timeout_ms** properties.
https://github.com/kyma-project/kyma/issues/4180
> Update Kyma subscription examples

- monitoring-custom-metrics/main.go
> Generate random temperature

- monitoring-custom-metrics/deployment/deployment.yaml
- Updated to the newest version
> Bump Custom Metrics example

- CODEOWNERS
> Add missing TW codeowners

- event-email-service/deployment/deployment.yaml
- event-subscription/lambda/deployment/sample-publisher.yaml
- event-subscription/service/example-publisher.yaml
- event-subscription/service/example-subscriber.yaml
- gateway/service/deployment.yaml
- http-db-service/deployment/deployment.yaml
- monitoring-custom-metrics/Gopkg.lock
- monitoring-custom-metrics/Gopkg.toml
- monitoring-custom-metrics/Makefile
- monitoring-custom-metrics/deployment/deployment.yaml
- service-binding/service/deployment/http-db-service.yaml
- tests/http-db-service/Gopkg.lock
- tests/http-db-service/Gopkg.toml
- tests/http-db-service/Makefile
- tracing/Gopkg.lock
- tracing/Gopkg.toml
- tracing/Makefile
- tracing/deployment/deployment.yaml
- Updated deprecated API versions
Fixes: kyma-project/kyma/issues/5659
> Update API versions

- monitoring-custom-metrics/deployment/deployment.yaml
- Fix the deployment validation by adding selector field and resource limits
See https://github.com/kyma-project/kyma/issues/6124
> Fix deployment validation

- monitoring-alert-rules/README.md
- monitoring-alert-rules/deployment/alert-rule.yaml
- monitoring-custom-metrics/README.md
- Update monitoring examples
See https://github.com/kyma-project/kyma/issues/6124
> Update monitoring examples

- CODEOWNERS
- tracing/README.md
- Add a note to the example - adjusting the value for trace sampling 
- Add the link to the troubleshooting guide
- Update the codeowners file
See also #121
> Add a note to the example

- service-binding/service/deployment/http-db-service.yaml
- Fixed deployment selector expression in one of the examples
- ...
- ...
> Deployment used wrong selector expression

- orders-service/docs/openapi.yaml
- Updated the orders-service spec.
> Update OpenAPI spec in the orders-service example

- .github/pull-request-template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- http-db-service/config/service.go
- http-db-service/internal/repository/db.go
- orders-service/Dockerfile
- rafter/README.md
- Changed excluding terms into inclusive alternatives
See also #https://github.com/kyma-project/community/issues/515
> Change excluding terms into inclusive alternatives

- event-email-service/Makefile
- http-db-service/Makefile
- http-db-service/README.md
- monitoring-custom-metrics/Makefile
- orders-service/Makefile
- orders-service/chart/Chart.yaml
- tests/http-db-service/Makefile
- tracing/Makefile
- tracing/README.md
- ...
- ...
- ...
https://github.com/kyma-project/test-infra/pull/3537
> replace master with main

- orders-service/README.md
- rafter/README.md
- Fix the broken links in the README files
> Fix the broken link

- README.md
Because this repository is not currently maintained by any specific Kyma team, but we don't want to delete it yet, we can add a note explaining that the examples are not always current. 
This issue was discussed on the Kyma content [SIG](https://kyma-project.io/community/collaboration/#special-interest-group-working-group-special-interest-group-working-group-sig-special-interest-group) meeting.
- Add note to examples README.md file about the state of the repository
N/a
> Add note to examples README.md file about the state of the repository

- .github/pull-request-template.md
- CONTRIBUTING.md
> Fixed dead links

- service-binding/lambda/README.md
> fix broken kubeless link

- incluster_eventing/README.md
- incluster_eventing/emitter/config.yaml
- incluster_eventing/emitter/handler.js
- incluster_eventing/emitter/package.json
- incluster_eventing/receiver/config.yaml
- incluster_eventing/receiver/handler.js
- incluster_eventing/receiver/package.json
- provide exemplary code for the asynchronous connection between functions
https://github.com/kyma-project/kyma/issues/10845
> Incluster eventing

- incluster_eventing/emitter/handler.js
- incluster_eventing/emitter/package.json
- add axios import 
https://github.com/kyma-project/kyma/issues/13635
> add axios import

- orders-service/internal/handler/order_handler.go
- orders-service/internal/service/order_service.go
- orders-service/internal/store/memory_store.go
- orders-service/internal/store/redis_store.go
- orders-service/internal/store/store.go
- Add endpoint allowing to read current storage type
https://github.com/kyma-project/kyma/issues/13872
https://github.com/kyma-project/kyma/pull/13975#discussion_r850272993
> Readible storeage type for additional test assertions

- CODEOWNERS
- incluster_eventing/src/emitter-fn/config.yaml
- reference main branch in the sample git function
> Fix Git reference in in-cluster eventing example

- gateway/README.md
- Fix link in Gateway README.md
> fix link in Gateway README

- incluster_eventing/Makefile
- incluster_eventing/k8s-resources/emitter-fn.yaml
- incluster_eventing/k8s-resources/receiver-fn.yaml
- incluster_eventing/src/render-manifests.sh
- migrate sample functions and apirules to current api versions
https://github.com/kyma-project/kyma/issues/13828
> Upgrade sample function to v1alpha2

- gateway/README.md
> fix broken link in examples repo

- kiali/README.md
- kiali/values.yaml
- adds a new tutorial for kiali
https://github.com/kyma-project/kyma/issues/15410
> tutorial for kiali

- README.md
- kiali/README.md
- kiali/apirule.yaml
- kiali/tracing-values.yaml
- Add APIRule example to expose Kiali
- Switch to token based authentication and add more explanation about auth strategies
https://github.com/kyma-project/kyma/issues/15410
> Enhance Kiali example

- trace-demo/README.md
- trace-demo/istio-values.yaml
- trace-demo/tracepipeline.yaml
- trace-demo/values.yaml
- Add a new example for how to deploy the OTEL demo app
> Otel tracing demo

- loki/README.md
- loki/logpipeline.yaml
- the overview consisted only of notes, changed it to be more readable
- improved file and resource naming
- ...
https://github.com/kyma-project/kyma/issues/15828
> improvments to loki tutorial

- trace-demo/README.md
- trace-demo/values.yaml
- updated to otel-demo 0.11.1
- used new envOverride feature to configure the custom otel-collector
- ...
> updated to newest chart version and removed avoidable overrides

- loki/README.md
- loki/apirule.yaml
- loki/busola-config.yaml
- loki/dashboard-configmap.yaml
- Added apirule file for grafana;
- Added grafana exposure section to README;
https://github.com/kyma-project/kyma/issues/15828
> Exposing the deployed Grafana in the Loki tutorial

- loki/README.md
> fixed broken link in loki tutorial

- trace-demo/README.md
- trace-demo/istio-values.yaml
- trace-demo/values.yaml
- Adapt service names according to https://github.com/kyma-project/kyma/pull/16226
https://github.com/kyma-project/kyma/issues/16198
> Adapt service names in the trace demo

- custom-serverless-runtime-image/Dockerfile
- custom-serverless-runtime-image/kubeless/ce.py
- custom-serverless-runtime-image/kubeless/kubeless.py
- custom-serverless-runtime-image/kubeless/requirements.txt
- custom-serverless-runtime-image/kubeless/tracing.py
- Sync example after changes in the python runtime https://github.com/kyma-project/kyma/pull/15774
https://github.com/kyma-project/kyma/pull/15774
Fixes https://github.com/kyma-project/examples/issues/211
> Sync kubeless.py

- prometheus/monitoring-custom-metrics/README.md
Add links to files that have been created by PR #224.
- Set links to raw files in kubectl commands that have not been existing in previous PR
> Replace missing links in Prometheus example by raw files

- prometheus/README.md
- prometheus/values.yaml
- removed generic label mapping as it will cause trouble in a generic way when labels have dynamic values
- provided full set of standard kubernetes labels with proper naming
- added scheme annotations also for pod scraping
- moved alertmanager setup to a dedicated alerting section
> refined scraping by annotation in prometheus tutorial

- orders-service/README.md
- Fix broken link for Orders function.yaml
- ...
- ...
> broken link fix

- trace-demo/README.md
- fix link to browser instrumentation
> fix link to browser instrumentation

- metrics-otlp/README.md
- metrics-otlp/metrics-agent-values.yaml
- metrics-otlp/metrics-gateway-values.yaml
- trace-demo/README.md
- trace-demo/values.yaml
- update otel-collector versions
- update otel-demo app version
- configure istio cni initicontainer workaround for demo app (https://istio.io/latest/docs/setup/additional-setup/cni/)
- improved collector setup to use named filters
- improved collector setup to differentiate prometheus receivers by topic
- improved istio scrape setup
> improved telemetry examples

- trace-demo/README.md
> fixed namespace in otel-demo example

- CODEOWNERS
- scale-to-zero-with-keda/README.md
- scale-to-zero-with-keda/k8s-resources/http-proxy-fn.yml
- scale-to-zero-with-keda/k8s-resources/scalable-worker-fn.yml
- adjust the keda installation part
- bump nodejs runtime versions
- bump subscription api version
https://github.com/kyma-project/keda-manager/pull/213
> Adjust keda example to latest kyma changes

- jaeger/README.md
- kiali/README.md
- loki/README.md
- Adjust the overview section in `jaegar`, `kiali` and `loki` examples to not assume that they already exist in Kyma installation.
- Change `apirule.yaml` file reference in `loki` example to not assume that the file exists locally.
- Fix broken links in `jaegar` example.
kyma-project/kyma#17637
> Adjust observability examples

- metrics-otlp/README.md
- metrics-otlp/metrics-agent-values.yaml
update of otel-collector version
- updated otel-collector to latest version
- switched metrics-agent to istio sidecar injection by label, so that the injection is independent from any namespace labelling
- ...
> update of otel-collector in metrics example

- trace-demo/README.md
- trace-demo/values.yaml
- updated the version of the otel-demo app to 0.22.4
- reordered the values.yaml entries to correspond to upstream listing
- ...
> version update for otel-demo example

- .github/workflows/cutom-metrics-docker-image.yaml
- Adds a GitHub Action workflow to build and publish the metrics image
> Add custom metric image build-n-publish workflow

- README.md
- gateway/README.md
- orders-service/README.md
- Update links for the OS website domain change
> Update links for the domain change

- kiali/values.yaml
- Fix map parsing error in Kiali example values
> Fix map parsing error in Kiali example values

- trace-demo/README.md
- trace-demo/values.yaml
- update to otel-demo 0.24.0
- remove outdated warning about tracing feature
- add metrics endpoint configuration already
- increase memory limits for demo component typically crashing with OOM
> update to otel-demo 0.24.0

- prometheus/monitoring-custom-metrics/deployment/deployment.yaml
- update custom-metrics to newest image version
- ...
- ...
> update custom-metrics to newest image version

- prometheus/prometheus.md
- Add preriquisite to have Istio enabled in Prometheus example
> Add preriquisite to have Istio enabled in Prometheus example

- event-email-service/package-lock.json
- event-email-service/package.json
- Bump event-email-service dependencies to make depandabot happy
> Bump event-email-service dependencies

- custom-serverless-runtime-image/kubeless/requirements.txt
- orders-service/function/package.json
- Bump dependencies to make dependabot happy
> Bump dependencies
