event-subscription/service/README.md

Fix the event-subscription example README to have the correct event source namespace in the publish command example

Fix the event source namespace in the publish ex.

---

CONTRIBUTING.md

- Removed the invalid CI information from the `CONTRIBUTING.md` document
- Added a reference to the Prow documentation 
See  https://github.com/kyma-project/test-infra/issues/72

Remove the invalid CI information

---

event-email-service/deployment/deployment.yaml
event-subscription/lambda/deployment/sample-publisher.yaml
event-subscription/service/example-publisher.yaml
event-subscription/service/example-subscriber.yaml
gateway/service/deployment.yaml
http-db-service/deployment/deployment.yaml
monitoring-custom-metrics/deployment/deployment.yaml
service-binding/service/deployment/http-db-service.yaml
tracing/deployment/deployment.yaml

Istio side car injection is enabled by default on any newly created namespace (having env=true label). With that, it is not required to enable it additionally on any deployment. So I removed it from the examples to keep the code focused on the example.

removed annotations for side-car injection

---

http-db-service/docs/api/api.yaml
http-db-service/handler/events/order_created.go
http-db-service/handler/events/order_created_test.go
http-db-service/handler/order.go
http-db-service/handler/order_test.go
http-db-service/handler/response/response.go
http-db-service/handler/utils/utils.go
http-db-service/internal/repository/api.go
http-db-service/main.go

- Add a new path `/events/order/created`
- Updated the server to add new handler
See also https://github.com/kyma-project/kyma/issues/3960

Add an example API for events to http-db-service

---

event-subscription/lambda/README.md
event-subscription/service/README.md
examples-chart/templates/tests/event-subscription/lambda/Pod.yaml

Description
w.r.t https://github.com/kyma-project/kyma/pull/4956 certain components from the event-bus have been refactores and this PR proposes changes in the corresponding example references
- Update event-bus-publish.kyma-system:8080 => event-publish-service.kyma-system:8080

Change eventing publish urls to the new ones

---

CODEOWNERS

Since Barbara Sz. (@bszwarc) left us in September and is no longer an active contributor, she should be removed from CODEOWNERS.  
At the same time, Justyna Sz. (@superojla) joined us in September and has been contributing to Kyma documentation, so it's time to add her to CODEOWNERS. 
- Remove @bszwarc from documentation CODEOWNERS
- Add @superojla to documentation CODEOWNERS

Update Examples documentation CODEOWNERS

---

tracing/README.md

- Changed `master` to `main` in docs (leftovers)
See issue https://github.com/kyma-project/community/issues/515

Rename master to main (leftover)

---

CODEOWNERS

As Karolina, Justyna and Basia are no longer active contributors to the project, they must be removed from the CODEOWNERS. 
- Remove @kazydek, @superojla, and @bszwarc from CODEOWNERS

Remove kazydek, superojla, and bszwarc from CODEOWNERS

---

CONTRIBUTING.md

Due to a [recent documentation restructure](https://github.com/kyma-project/community/pull/608), the README template was moved to another place, which [broke the link](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/examples-governance-nightly/1462949035013836800) to said template. This PR fixes the link. 
- Fix a link to the README template

Fix a broken link to the README template

---

CODEOWNERS

As @grego952 has been working with Kyma for over 3 months as a Technical Writer and has gained expertise in this domain, he should be added to the documentation CODEOWNERS.
- Add @grego952 to Examples documentation CODEOWNERS
**Related issue**
[#13077 ](https://github.com/kyma-project/kyma/issues/13077)

Add Grzegorz as a documentation CODEOWNER in Examples

---

monitoring-custom-metrics/deployment/service-monitor.yaml

- A servicemonitor can be placed in any namespace
- The prometheus label is not required anymore on a servicemonitor
- ...

removed unneeded namespace and label from monitoring example

---

orders-service/README.md

This PR changes outdated and/or broken links pointing to documentation on the Website to ones that point to documentation on GitHub. 
- Change outdated Website links to GitHub ones in the [`orders-service` README](https://github.com/kyma-project/examples/blob/main/orders-service/README.md).
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/examples-governance-nightly/1508247644214923264

Change outdated Website links to GitHub ones

---

CONTRIBUTING.md

Since we changed the way how to [set up a new repository in Kyma](https://kyma-project.io/community/guidelines/repository-guidelines/01-new-repository-settings), some links and sections became outdated. This PR fixes a broken link to the README.md template.
- Fix the broken link to the README.md template

Fix the broken link to the README.md template

---

orders-service/Dockerfile

- use alpine to be able to exec sh in the resulting pod
https://github.com/kyma-project/kyma/issues/13872

Use alpine to exec sh in e2e tests

---

prometheus/README.md
prometheus/alertmanager-values.yaml
prometheus/values.yaml

- Add instructions to set up alerting channels to Prometheus example
https://github.com/kyma-project/kyma/issues/15914

Add instructions to set up alerting channels to Prometheus example

---

incluster_eventing/src/emitter-fn/config.yaml
incluster_eventing/src/emitter-fn/handler.js
incluster_eventing/src/emitter-fn/package.json
incluster_eventing/src/receiver-fn/config.yaml

Updates in cluster eventing example to reflect the new cloud-events api in nodejs runtimes 
Depends on https://github.com/kyma-project/kyma/pull/16116

Reflect changes in cloudevents api

---

prometheus/README.md

- If admission webhooks are being installed for kube prometheus stack then these would interfere with the prometheusrules or other prometheus resources being created in `kyma-system` namespace. So add a exclusion for same.

Exclude system namespace from admission webhooks in kube prometheus stack

---

prometheus/README.md
prometheus/values.yaml

The admission webhooks of the kube-prometheus-stack can interfere with the Kyma monitoring stack. To avoid failures while deploying Kyma, the webhooks are disabled by default.
- Disable admission webhooks for Prometheus example
- Adapt README

Disable admission webhooks in Prometheus example

---

prometheus/values.yaml

The prometheus-operator is not starting up as the webhooks are disabled but still webhook tls cert injection is expected.
After fixing that, I fould that the grafana datasource sidecar is running as initContainer and faces connectivity problems with istio CNI. FIxed that as well by providing dedicated secutiry config.
Prometheus has an initContainer as well. However the traffic interception for the istio sidecar is disabled (only used for certificate injection), so there is no problem. Furthermore, there is no way to configure the securityContext for the container via the prometheus-operator, so I ignored that.
- fix prometheus-operator startup problem by disabling webhook tls additional to the webhook
- add securitycontext for …

fix cni problems in prometheus example

---

incluster_eventing/k8s-resources/emitter-fn.yaml
incluster_eventing/k8s-resources/receiver-fn.yaml
incluster_eventing/src/emitter-fn/config.yaml
incluster_eventing/src/receiver-fn/config.yaml

- Use latest nodejs v18 in the serverless examples
https://github.com/kyma-project/kyma/issues/16765

Use nodejs18 runtime in serverless examples

---

trace-demo/values.yaml

For specific features of istio, istio must have a chance to determine the protocol supported by an exposed port. For that it uses naming conventions like "http-metrics" for a service port, or it uses the "appProtocol" attribute of a service port.
In the otel-demo app the name of the services is set to "tcp-service" and no appProtocol is defined. With that it cannot determine the protocol and no spans are created at all for most of the communication happening.
As a workaround I overwrote the port definitions to set a name explicit. Later on we should contribute to upstream to simply set the protocol per service.
- overwriting most service port names with the appropriate protocol prefix to make istio behave proper
- using the …

adjust OTEL demo to have proper protocols defined in the used k8s services

---

kiali/README.md
kiali/values.yaml
prometheus/values.yaml

- switch to custom prometheus instead of deprecated built-in solution
- enable istio sidecar for incoming traffic to prometheus to allow secure communication by kiali
- enable istio for grafana to have secure communication to prometheus

use custom prometheus for kiali example

---

jaeger/README.md
loki/README.md
trace-demo/README.md

- add a prerequisite to ensure that the Telemetry module is enabled for the following examples: `jaeger`, `loki` and `trace-demo`
kyma-project/kyma#18190

Add Telemetry module as a prerequisite for observability examples

---

kiali/README.md
prometheus/README.md
prometheus/values.yaml

The example used in-memory persistence to keep it lightweight. Indeed, it is better to have persistence enabled by default  based on PVCs as usual for a typical in-cluster setup
- configured retention times for data by time and size
- configured persistency by PVC
- configured resource setting for all relevant components
- fixed grafana serviceMonitor

Add default persistence settings to prometheus example

---

scale-to-zero-with-keda/README.md
scale-to-zero-with-keda/k8s-resources/http-proxy-fn.yml
scale-to-zero-with-keda/k8s-resources/scalable-worker-fn.yml
scale-to-zero-with-keda/src/http-proxy-fn/handler.js
scale-to-zero-with-keda/src/http-proxy-fn/package.json

- use recommended `emitCloudEvent` way to send CE from a function
- fix test command - content type matching the actual content in the curl command
- fix git reference for the sample functions

Fix scale to zero example

---

event-email-service/README.md
gateway/README.md
http-db-service/README.md
jaeger/README.md
kiali/README.md
loki/README.md
metrics-otlp/README.md
metrics-otlp/metrics-agent-values.yaml
prometheus/README.md
prometheus/monitoring-alert-rules/README.md
prometheus/monitoring-custom-metrics/README.md
prometheus/monitoring-grafana-dashboard/README.md
service-binding/lambda/README.md
service-binding/service/README.md
trace-demo/README.md
tracing/README.md

The variable name "KYMA_NS" was giving a wrong intention to some users and they assumed the value should be "kyma-system". The intention is exactly the opposite.
So I renamed the env variable to K8S_NAMESPACE and applied that to all examples
- Renamed all env variable for namespaces to K8S_NAMESPACE

unified namespace variable naming

---

scale-to-zero-with-keda/README.md
scale-to-zero-with-keda/k8s-resources/peer-authentication.yaml
scale-to-zero-with-keda/k8s-resources/scalable-worker-fn.yml

- add instructions to adjust the prometheus target namespace
- allow non mtls trafic from keda to custom prometheus

Configure connectivity between keda & custom prometheus stack

---

prometheus/values.yaml

- When istio is enabled the createSecret Job fails. The injected side car prevents it. So exclude istio injection here.
-  More info: https://github.com/prometheus-community/helm-charts/issues/479
- ...
- ...

fix: Allow createSecret job to create secrets when istio is enabled

---

README.md
prometheus/README-old.md
prometheus/README.md
prometheus/monitoring-alert-rules/README.md
prometheus/monitoring-custom-metrics/README.md
prometheus/monitoring-grafana-dashboard/README.md

- Prepare for archiving the repo
- ...
- ...

Add archive notes to the repo
